Bugfix + optimize [semver:minor] (#48)
Address a few known bugs and improve/optimize the config logic, and install logic.

Minor changes:

reconstructed skip-install-check parameter
New bash optimization required re-doing the parameter. Should work essentially the same but with this much change to the logic I did not want to consider this a patch in the case this might affect a user differently. Settling on a minor change, as this shouldn't cause errors.
Bug Fix:

Previously, if you had selected to install AWS CLI v2, but v1 was already installed, the orb would exit without error and skip the install thinking it was already installed.
Orb now checks to see if the installed version matched the config version, if they do not match, the installed version will be replaced.
#47 Fix setting default AWS region
#42 updated tests show success for both versions of CLI on each executor (windows not included)
Other:

Rework install logic
Now checks to see if AWS is already installed, and what version.
Skips if the version installed matches the desired version. If not, the installed version will be replaced automatically.
#45 Provide better error message when attempting to install v1 on a non-python image
Increased and improved testing.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,7 +2,7 @@ version: 2.1
 
 orbs:
   orb-tools: circleci/orb-tools@9.0
-  aws-cli: circleci/aws-cli@dev:alpha
+  aws-cli: circleci/aws-cli@<<pipeline.parameters.dev-orb-version>>
 
 # Pipeline parameters
 parameters:
@@ -18,7 +18,13 @@ parameters:
 executors:
   without-less:
     docker:
-      - image: circleci/python:3.7
+      - image: cimg/base:stable
+  python:
+    docker:
+      - image: cimg/python:3.8
+  awsv2preinstalled:
+    docker:
+      - image: cibuilds/aws:2.0.6
   macos:
     macos:
       xcode: 11.4
@@ -30,8 +36,10 @@ executors:
 integration_tests: &integration_tests
   [
     integration-test-install-v2,
+    # v1-docker,
+    integration-test-skip-install,
     integration-test-install-v1,
-    integration-test-skip-install
+    replace-pip-aws-test
   ]
 
 jobs:
@@ -41,8 +49,18 @@ jobs:
         type: executor
     executor: <<parameters.executor>>
     steps:
-      - checkout
       - aws-cli/setup
+      - run:
+          name: Check installed AWS CLI version
+          command: |
+            which aws
+            echo $(aws --version)
+            if ! echo "$(aws --version)" | grep -q "(aws-cli/2)"; then
+                echo "Version 2 installed successfully."
+            else
+                echo "Incorrect version installed"
+                exit 1
+            fi
       - run:
           name: Test that paging is disabled
           command: |
@@ -52,7 +70,10 @@ jobs:
               --filters "Name=platform,Values=windows" "Name=root-device-type,Values=ebs"
 
   integration-test-install-v1:
-    executor: aws-cli/default
+    parameters:
+      executor:
+        type: executor
+    executor: <<parameters.executor>>
     steps:
       - checkout
       - aws-cli/setup:
@@ -60,20 +81,47 @@ jobs:
       - run:
           name: Check latest v1 version is installed.
           command: |
-            aws --version
-            if [ "$(pip list --outdated | grep -c "awscli")" -ge 1 ]; then
-              echo "aws version is outdated"
+            which aws
+            if aws --version 2>&1 | grep -q 'aws-cli\/1.\d*.\d*'; then
+              echo AWS CLI v1 is installed
+            else
+              echo Wrong CLI version.
               exit 1
             fi
 
   integration-test-skip-install:
     # This image is suitable for the test as it comes with aws preinstalled
-    machine:
-      image: ubuntu-1604:201903-01
+    parameters:
+      executor:
+        type: executor
+    executor: <<parameters.executor>>
     steps:
-      - checkout
+      - aws-cli/install:
+          version: "2"
       - aws-cli/setup:
+          version: "1"
           skip-install-check: true
+
+  replace-pip-aws-test:
+    docker:
+      - image: cimg/python:3.8
+    steps:
+      - run: pip install awscli
+      - run: which aws
+      - aws-cli/setup:
+          version: "2"
+          skip-install-check: true
+      - run:
+          name: Check installed AWS CLI version
+          command: |
+            which aws
+            echo $(aws --version)
+            if ! echo "$(aws --version)" | grep -q "(aws-cli/2)"; then
+                echo "Version 2 installed successfully."
+            else
+                echo "Incorrect version installed"
+                exit 1
+            fi
 
 workflows:
   lint-pack_validate_deploy-dev:
@@ -98,9 +146,21 @@ workflows:
       - integration-test-install-v2:
           matrix:
             parameters:
-              executor: [aws-cli/default, without-less, macos, machine]
-      - integration-test-install-v1
-      - integration-test-skip-install
+              executor: [aws-cli/default, without-less, macos, machine, python, awsv2preinstalled]
+      - integration-test-install-v1:
+          matrix:
+            parameters:
+              executor: [macos, machine, python]
+      - integration-test-skip-install:
+          matrix:
+            parameters:
+              executor: [macos, machine, python]
+      - replace-pip-aws-test
+      # This job is supposed to fail, do not run it unless for testing purposes.
+      # This job fails with a more useful error message when a user wants to install CLI V1 on an image without python.
+      # - integration-test-install-v1:
+      #     name: v1-docker
+      #     executor: without-less
 
       - orb-tools/dev-promote-prod-from-commit-subject:
           orb-name: circleci/aws-cli
diff --git a/src/commands/install.yml b/src/commands/install.yml
--- a/src/commands/install.yml
+++ b/src/commands/install.yml
@@ -6,109 +6,152 @@ parameters:
     type: enum
     enum: ["1", "2"]
     default: "2"
-  skip-install-check:
-    description: |
-      Set to true to skip checking for existing installations before installing.
-    type: boolean
-    default: false
   disable-aws-pager:
     description: |
       Set to false to skip forceful disabling of all AWS CLI output paging.
     type: boolean
     default: true
+  skip-install-check:
+    description: |
+      Set to true to skip checking for existing installations before installing.
+    type: boolean
+    default: false
+
 
 steps:
   - run:
       name: Install AWS CLI v<<parameters.version>>
       command: |
-        AWS_CLI_VERSION_SELECTED=<<parameters.version>>
-        case $AWS_CLI_VERSION_SELECTED in
-          "1")
-            if [ "<<parameters.skip-install-check>>" == "false" ] && which aws > /dev/null; then
-                echo "The AWS CLI is already installed. Skipping."
-                exit 0
-              fi
+        AWS_VER_REGEXP_2='aws-cli\/2.\d*.\d*'
+        AWS_VER_REGEXP_1='aws-cli\/1.\d*.\d*'
+        # initialize installed version to zero, to signify not installed (Or we want to ignore the installed version and re-install).
+        AWS_CLI_INSTALLED_VERSION="0"
+        AWS_CLI_VERSION_SELECTED="<<parameters.version>>"
 
-              export PIP=$(which pip pip3 | head -1)
-              if [[ -n $PIP ]]; then
-                if which sudo > /dev/null; then
-                  sudo $PIP install awscli --upgrade
-                else
-                  # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
-                  $PIP install awscli --upgrade --user
+        if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
+
+        if "<<parameters.skip-install-check>>" == "false"; then
+            if ! command -v aws --version >/dev/null 2>&1  ; then
+                echo AWS is not installed
+            else
+                echo AWS is currently installed.
+                if aws --version 2>&1 | grep -q $AWS_VER_REGEXP_2; then
+                    echo AWS CLI v2 is installed
+                    AWS_CLI_INSTALLED_VERSION="2"
                 fi
-              elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
-                cd
-                curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
-                unzip awscli-bundle.zip
-                if which sudo > /dev/null; then
-                  sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
-                else
-                  # This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
-                  awscli-bundle/install -b ~/bin/aws
+                if aws --version 2>&1 | grep -q $AWS_VER_REGEXP_1; then
+                    echo AWS CLI v1 is installed
+                    AWS_CLI_INSTALLED_VERSION="1"
                 fi
-                rm -rf awscli-bundle*
-                cd -
-              else
-                echo "Unable to install AWS CLI. Please install pip."
-                exit 1
-              fi
-          ;;
-          "2")
-            if [ "<<parameters.skip-install-check>>" == "false" ] && which aws > /dev/null; then
-                echo "The AWS CLI is already installed. Skipping."
-                exit 0
-              fi
+            fi
+        else
+            echo "Skipping version check. Installing CLI"
+        fi
 
-              if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
+        AWS_V2_UPDATE_PARAM=""
+        if aws --version 2>&1 | grep -q $AWS_VER_REGEXP_2; then
+            AWS_V2_UPDATE_PARAM="--update"
+        fi
 
-              cd /tmp || exit
+        #If the desired version of the CLI is not installed, install it.
+        if [[ $AWS_CLI_VERSION_SELECTED != $AWS_CLI_INSTALLED_VERSION ]]; then
 
-              # PLATFORM CHECK: mac vs. alpine vs. other linux
-              if uname -a | grep Darwin; then
-                SYS_ENV_PLATFORM=darwin
-              elif uname -a | grep Linux; then
-                SYS_ENV_PLATFORM=linux
-              else
-                echo "This platform appears to be unsupported."
-                uname -a
-                exit 1
-              fi
+            #uninstall AWS CLI if it is installed.
+            if which aws; then
+                echo Uninstalling old CLI
+                $SUDO rm -rf $(which aws)
+            fi
+            case $AWS_CLI_VERSION_SELECTED in
+                "1")
+                    if ! command -v python >/dev/null 2>&1 && ! command -v python3 >/dev/null 2>&1 ; then
+                        echo "Your environment does not seem to have Python installed, a requirement of the AWS CLI."
+                        echo "Please either utilize the AWS CLI v2, or select an envionment with Python installed."
+                        echo "Recommended image: cimg:/python:3.8"
+                        exit 1
+                    fi
+                    # install CLI v1
+                    export PIP=$(which pip pip3 | head -1)
+                    if [[ -n $PIP ]]; then
+                        if which sudo > /dev/null; then
+                            sudo $PIP install awscli --upgrade
+                        else
+                            # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
+                            $PIP install awscli --upgrade --user
+                        fi
+                    elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
+                        cd
+                        curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
+                        unzip awscli-bundle.zip
+                        if which sudo > /dev/null; then
+                            sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
+                        else
+                            # This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
+                            awscli-bundle/install -b ~/bin/aws
+                        fi
+                        rm -rf awscli-bundle*
+                        cd -
+                    else
+                        echo "Unable to install AWS CLI. Please install pip."
+                        exit 1
+                    fi
+                    # Installation check
+                    if aws --version &> grep -q "aws-cli/1"; then
+                        echo "AWS CLI V1 has been installed successfully"
+                        exit 0
+                    else
+                        echo "There was an issue installing the AWS CLI V1. Exiting."
+                        exit 1
+                    fi
+                ;;
+                "2")
+                    # install CLI v2
 
-              case $SYS_ENV_PLATFORM in
-                linux)
-                  curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-                  unzip awscliv2.zip
-                  $SUDO ./aws/install
-                  rm awscliv2.zip
-                  ;;
-                darwin)
-                  curl -sSL "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
-                  $SUDO installer -pkg AWSCLIV2.pkg -target /
-                  rm AWSCLIV2.pkg
-                  ;;
-                *)
-                  echo "This orb does not currently support your platform. If you believe it should, please consider opening an issue on the GitHub repository:"
-                  echo "https://github.com/CircleCI-Public/aws-cli-orb/issues/new"
-                  exit 1
-              esac
+                    cd /tmp || exit
 
-              # Installation check
+                    # PLATFORM CHECK: mac vs. alpine vs. other linux
+                    if uname -a | grep Darwin; then
+                        SYS_ENV_PLATFORM=darwin
+                    elif uname -a | grep Linux; then
+                        SYS_ENV_PLATFORM=linux
+                    else
+                        echo "This platform appears to be unsupported."
+                        uname -a
+                        exit 1
+                    fi
 
-              if aws --version &> grep -q "aws-cli/2"; then
-                echo "AWS CLI V2 has been installed successfully"
-                exit 0
-              else
-                echo "There was an issue installing the AWS CLI V2. Exiting."
-                exit 1
-              fi
-          ;;
-          *)
-            echo "An incorrect version selection has been made."
-            exit 1
-          ;;
-        esac
+                    case $SYS_ENV_PLATFORM in
+                        linux)
+                            curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+                            unzip awscliv2.zip
+                            $SUDO ./aws/install $AWS_V2_UPDATE_PARAM
+                            rm awscliv2.zip
+                            ;;
+                        darwin)
+                            curl -sSL "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
+                            $SUDO installer -pkg AWSCLIV2.pkg -target /
+                            rm AWSCLIV2.pkg
+                            ;;
+                        *)
+                            echo "This orb does not currently support your platform. If you believe it should, please consider opening an issue on the GitHub repository:"
+                            echo "https://github.com/CircleCI-Public/aws-cli-orb/issues/new"
+                            exit 1
+                        ;;
+                    esac
+                    # Installation check
+                    if aws --version &> grep -q "aws-cli/2"; then
+                        echo "AWS CLI V2 has been installed successfully"
+                        exit 0
+                    else
+                        echo "There was an issue installing the AWS CLI V2. Exiting."
+                        exit 1
+                    fi
+                ;;
+            esac
 
+        else
+            echo "The v${AWS_CLI_VERSION_SELECTED} AWS CLI is already installed."
+            exit 0
+        fi
   - when:
       condition: <<parameters.disable-aws-pager>>
       steps:
