Revert "Cli v2 Update [semver:major]"

diff --git a/src/commands/install.yml b/src/commands/install.yml
--- a/src/commands/install.yml
+++ b/src/commands/install.yml
@@ -1,11 +1,6 @@
 description: "Install the AWS CLI via Pip if not already installed."
 
 parameters:
-  version:
-    description: Which version of the CLI to install. Version "1" and "2" are currently available. Will default to "2"
-    type: enum
-    enum: ["1", "2"]
-    default: "2"
   skip-install-check:
     description: |
       Set to true to skip checking for existing installations before installing.
@@ -14,92 +9,34 @@ parameters:
 
 steps:
   - run:
-      name: Install AWS CLI v<<parameters.version>>
+      name: "Install AWS CLI"
       command: |
-        AWS_CLI_VERSION_SELECTED=<<parameters.version>>
-        case $AWS_CLI_VERSION_SELECTED in
-          "1")
-            if [ "<<parameters.skip-install-check>>" == "false" ] && which aws > /dev/null; then
-                echo "The AWS CLI is already installed. Skipping."
-                exit 0
-              fi
+        if [ "<<parameters.skip-install-check>>" == "false" ] && which aws > /dev/null; then
+          echo "The AWS CLI is already installed. Skipping."
+          exit 0
+        fi
 
-              export PIP=$(which pip pip3 | head -1)
-              if [[ -n $PIP ]]; then
-                if which sudo > /dev/null; then
-                  sudo $PIP install awscli --upgrade
-                else
-                  # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
-                  $PIP install awscli --upgrade --user
-                fi
-              elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
-                cd
-                curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
-                unzip awscli-bundle.zip
-                if which sudo > /dev/null; then
-                  sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
-                else
-                  # This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
-                  awscli-bundle/install -b ~/bin/aws
-                fi
-                rm -rf awscli-bundle*
-                cd -
-              else
-                echo "Unable to install AWS CLI. Please install pip."
-                exit 1
-              fi
-          ;;
-          "2")
-            if [ "<<parameters.skip-install-check>>" == "false" ] && which aws > /dev/null; then
-                echo "The AWS CLI is already installed. Skipping."
-                exit 0
-              fi
-
-              if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
-
-              cd /tmp || exit
-
-              # PLATFORM CHECK: mac vs. alpine vs. other linux
-              if uname -a | grep Darwin; then
-                SYS_ENV_PLATFORM=darwin
-              elif uname -a | grep Linux; then
-                SYS_ENV_PLATFORM=linux
-              else
-                echo "This platform appears to be unsupported."
-                uname -a
-                exit 1
-              fi
-
-              case $SYS_ENV_PLATFORM in
-                linux)
-                  curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-                  unzip awscliv2.zip
-                  $SUDO ./aws/install
-                  rm awscliv2.zip
-                  ;;
-                darwin)
-                  curl -sSL "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
-                  $SUDO installer -pkg AWSCLIV2.pkg -target /
-                  rm AWSCLIV2.pkg
-                  ;;
-                *)
-                  echo "This orb does not currently support your platform. If you believe it should, please consider opening an issue on the GitHub repository:"
-                  echo "https://github.com/CircleCI-Public/aws-cli-orb/issues/new"
-                  exit 1
-              esac
-
-              # Installation check
-
-              if aws --version &> grep -q "aws-cli/2"; then
-                echo "AWS CLI V2 has been installed successfully"
-                exit 0
-              else
-                echo "There was an issue installing the AWS CLI V2. Exiting."
-                exit 1
-              fi
-          ;;
-          *)
-            echo "An incorrect version selection has been made."
-            exit 1
-          ;;
-        esac
+        export PIP=$(which pip pip3 | head -1)
+        if [[ -n $PIP ]]; then
+          if which sudo > /dev/null; then
+            sudo $PIP install awscli --upgrade
+          else
+            # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
+            $PIP install awscli --upgrade --user
+          fi
+        elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
+          cd
+          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
+          unzip awscli-bundle.zip
+          if which sudo > /dev/null; then
+            sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
+          else
+            # This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
+            awscli-bundle/install -b ~/bin/aws
+          fi
+          rm -rf awscli-bundle*
+          cd -
+        else
+          echo "Unable to install AWS CLI. Please install pip."
+          exit 1
+        fi
